// VeriFiBIN 2.0 — Issuer Intelligence Database
// Proprietary knowledge base of known issuers, BIN prefixes and their 3DS/bypass behavior.
// IMPORTANT: All bypass probabilities are probabilistic inferences based on observed behavior.
// "Bypass" in this context refers to the 3DS2 Frictionless Flow or SCA Exemptions being applied,
// NOT to circumventing security illegally.

export type IssuerCategory =
  | "BANCO_TRADICIONAL"
  | "BANCO_DIGITAL"
  | "FINTECH_PREPAGO"
  | "FINTECH_VIRTUAL"
  | "CORPORATIVO"
  | "WHITE_LABEL"
  | "GOVERNO_SOCIAL"
  | "CRIPTO"

export type BypassMechanism =
  | "FRICTIONLESS_3DS2"       // 3DS2 active, but frictionless flow applied by issuer ACS
  | "SCA_EXEMPTION_B2B"       // PSD2 Secure Corporate Payment Exemption
  | "SCA_EXEMPTION_LOW_VALUE" // PSD2 Low-Value Transaction Exemption (<€30)
  | "SCA_EXEMPTION_TRA"       // Transaction Risk Analysis Exemption
  | "3DS_NOMINAL"             // 3DS enrolled but not effectively implemented (enrolled=Y, but no real ACS)
  | "GATEWAY_FALLBACK"        // Gateway does not implement full 3DS fallback
  | "NO_3DS"                  // No 3DS implementation at all
  | "UNKNOWN"

export type FrictionlessLikelihood = "MUITO_ALTA" | "ALTA" | "MEDIA" | "BAIXA" | "MUITO_BAIXA"

export interface IssuerProfile {
  name: string
  countryCode: string
  category: IssuerCategory
  binPrefixes: string[]
  threeDSActive: boolean
  frictionlessLikelihood: FrictionlessLikelihood
  bypassMechanism: BypassMechanism
  cvvDynamic: boolean
  multipleAttemptsAllowed: boolean
  silentDeclineRisk: boolean
  newCardDelay3DS: boolean // Some issuers activate 3DS only 24-72h after card issuance
  whiteLabel: boolean
  parentIssuer?: string
  technicalNotes: string
  alerts: string[]
}

// ─── Brazilian Issuers ─────────────────────────────────────────────────────

export const ISSUER_INTELLIGENCE: Record<string, IssuerProfile> = {
  // ── BRASIL: BANCOS TRADICIONAIS (3DS RÍGIDO) ──────────────────────────────
  CAIXA: {
    name: "Caixa Econômica Federal",
    countryCode: "BR",
    category: "BANCO_TRADICIONAL",
    binPrefixes: ["4011", "4055", "5363"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_BAIXA",
    bypassMechanism: "UNKNOWN",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: true,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "3DS forçado em todas as transações, incluindo valores de R$1. Declínio silencioso (delay de ~12s) quando 3DS falha. Bloqueia cartão após falha no iframe.",
    alerts: ["3DS_OBRIGATORIO", "SILENT_DECLINE_RISK", "IFRAME_FAILURE_BLOCKS_CARD"],
  },
  ITAU: {
    name: "Itaú Unibanco",
    countryCode: "BR",
    category: "BANCO_TRADICIONAL",
    binPrefixes: ["4054", "4024", "5041"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_BAIXA",
    bypassMechanism: "UNKNOWN",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Rejeita compra no 1º retry sem 3DS. Nunca aprova sem 3DS ativo. Integração direta com app Itaú para push notification.",
    alerts: ["3DS_OBRIGATORIO", "REJEITA_RETRY_SEM_3DS"],
  },
  BRADESCO: {
    name: "Bradesco",
    countryCode: "BR",
    category: "BANCO_TRADICIONAL",
    binPrefixes: ["4024", "5136"],
    threeDSActive: true,
    frictionlessLikelihood: "BAIXA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "3DS ativo com integração via app push. Cartões Next (white-label) são mais permissivos que o Bradesco normal.",
    alerts: ["3DS_ATIVO"],
  },
  BANCO_DO_BRASIL: {
    name: "Banco do Brasil",
    countryCode: "BR",
    category: "BANCO_TRADICIONAL",
    binPrefixes: ["4514"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_BAIXA",
    bypassMechanism: "UNKNOWN",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Bloqueio automático se 3DS falhar. Débito com 3DS obrigatório.",
    alerts: ["3DS_OBRIGATORIO", "BLOQUEIO_AUTOMATICO_FALHA_3DS"],
  },

  // ── BRASIL: BANCOS DIGITAIS (3DS ATIVO, FRICTIONLESS VARIÁVEL) ───────────
  NUBANK: {
    name: "Nubank",
    countryCode: "BR",
    category: "BANCO_DIGITAL",
    binPrefixes: ["5529", "4111"],
    threeDSActive: true,
    frictionlessLikelihood: "MEDIA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: true,
    newCardDelay3DS: true,
    whiteLabel: false,
    technicalNotes: "3DS ativo. Frictionless aplicado em transações abaixo de R$100 com IP/device histórico limpo. Cartão virtual emitido na hora: 3DS só ativa após 1ª compra. Retorna 'aguarde' sem processar (silent decline) em casos de risco.",
    alerts: ["FRICTIONLESS_POSSIVEL_VALOR_BAIXO", "NOVO_CARTAO_SEM_3DS_INICIAL", "SILENT_DECLINE_RISK"],
  },
  BANCO_INTER: {
    name: "Banco Inter",
    countryCode: "BR",
    category: "BANCO_DIGITAL",
    binPrefixes: ["5541", "4514"],
    threeDSActive: true,
    frictionlessLikelihood: "MEDIA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Antifraude forte. Frictionless possível em horários específicos (domingos à noite) e compras digitais com device reconhecido. Cartões adicionais (dependentes) emitidos sem 3DS inicial.",
    alerts: ["FRICTIONLESS_POSSIVEL_HORARIO_ESPECIFICO", "CARTAO_DEPENDENTE_SEM_3DS"],
  },
  C6_BANK: {
    name: "C6 Bank",
    countryCode: "BR",
    category: "BANCO_DIGITAL",
    binPrefixes: ["5162"],
    threeDSActive: true,
    frictionlessLikelihood: "MEDIA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: true,
    whiteLabel: false,
    technicalNotes: "3DS quase sempre ativo. Frictionless com device repetido e valor baixo. Cartão emitido na hora, mas 3DS entra após 48h.",
    alerts: ["FRICTIONLESS_POSSIVEL_DEVICE_REPETIDO", "NOVO_CARTAO_3DS_DELAY_48H"],
  },
  PAGBANK: {
    name: "PagBank (PagSeguro)",
    countryCode: "BR",
    category: "BANCO_DIGITAL",
    binPrefixes: ["5273", "5399"],
    threeDSActive: true,
    frictionlessLikelihood: "MEDIA",
    bypassMechanism: "GATEWAY_FALLBACK",
    cvvDynamic: false,
    multipleAttemptsAllowed: true,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Modo sandbox do PagSeguro nunca exibe 3DS. Em produção, frictionless possível quando gateway não solicita iframe. Permite até 3 tentativas por IP.",
    alerts: ["GATEWAY_FALLBACK_POSSIVEL", "SANDBOX_SEM_3DS", "MULTIPLAS_TENTATIVAS"],
  },
  DIGIO: {
    name: "Digio",
    countryCode: "BR",
    category: "BANCO_DIGITAL",
    binPrefixes: ["5294"],
    threeDSActive: true,
    frictionlessLikelihood: "BAIXA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: true,
    whiteLabel: false,
    technicalNotes: "Demora até 3 dias para ativar VBV após ativação do cartão.",
    alerts: ["NOVO_CARTAO_3DS_DELAY_72H"],
  },

  // ── BRASIL: CORPORATIVOS (ALTA CHANCE DE BYPASS VIA ISENÇÃO B2B) ──────────
  BRADESCO_PJ: {
    name: "Bradesco Empresarial",
    countryCode: "BR",
    category: "CORPORATIVO",
    binPrefixes: ["4266"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "SCA_EXEMPTION_B2B",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Mesmo com 3DS registrado, passa direto em gateways que aplicam isenção B2B. Cartões corporativos operam com risk-score interno diferenciado.",
    alerts: ["ISENCAO_B2B_PROVAVEL", "BYPASS_CORPORATIVO"],
  },
  ITAU_PJ: {
    name: "Itaú Empresarial",
    countryCode: "BR",
    category: "CORPORATIVO",
    binPrefixes: ["5521", "5521"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "SCA_EXEMPTION_B2B",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Gateway suprime 3DS por perfil de empresa. Roteamento por CNPJ e trusted device scoring.",
    alerts: ["ISENCAO_B2B_PROVAVEL", "BYPASS_CORPORATIVO"],
  },
  SANTANDER_PJ: {
    name: "Santander PJ",
    countryCode: "BR",
    category: "CORPORATIVO",
    binPrefixes: ["5136"],
    threeDSActive: true,
    frictionlessLikelihood: "ALTA",
    bypassMechanism: "SCA_EXEMPTION_B2B",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Dispara 3DS em poucos casos. Fallback ignorado em IP confiável.",
    alerts: ["ISENCAO_B2B_PROVAVEL", "BYPASS_CORPORATIVO"],
  },

  // ── BRASIL: WHITE-LABELS ──────────────────────────────────────────────────
  NEXT: {
    name: "Next (Bradesco)",
    countryCode: "BR",
    category: "WHITE_LABEL",
    binPrefixes: ["5136"],
    threeDSActive: true,
    frictionlessLikelihood: "ALTA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: true,
    parentIssuer: "BRADESCO",
    technicalNotes: "Mais permissivo que o Bradesco normal. Comportamento 3DS diferente do banco pai.",
    alerts: ["WHITE_LABEL_COMPORTAMENTO_DIFERENTE"],
  },
  NEON: {
    name: "Neon (Banco Votorantim)",
    countryCode: "BR",
    category: "WHITE_LABEL",
    binPrefixes: ["5274"],
    threeDSActive: true,
    frictionlessLikelihood: "MEDIA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: true,
    parentIssuer: "BANCO_VOTORANTIM",
    technicalNotes: "Varia por device. Comportamento diferente do banco pai.",
    alerts: ["WHITE_LABEL_COMPORTAMENTO_DIFERENTE"],
  },
  MELIUZ: {
    name: "Méliuz (Banco Pan)",
    countryCode: "BR",
    category: "WHITE_LABEL",
    binPrefixes: ["5294"],
    threeDSActive: true,
    frictionlessLikelihood: "MEDIA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: true,
    whiteLabel: true,
    parentIssuer: "BANCO_PAN",
    technicalNotes: "3DS fraco nos primeiros dias após emissão.",
    alerts: ["WHITE_LABEL_COMPORTAMENTO_DIFERENTE", "NOVO_CARTAO_3DS_FRACO"],
  },
  SUPERDIGITAL: {
    name: "Superdigital (Santander)",
    countryCode: "BR",
    category: "WHITE_LABEL",
    binPrefixes: ["5136"],
    threeDSActive: false,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "NO_3DS",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: true,
    parentIssuer: "SANTANDER",
    technicalNotes: "Sem 3DS obrigatório. Comportamento muito diferente do Santander normal.",
    alerts: ["SEM_3DS", "WHITE_LABEL_COMPORTAMENTO_DIFERENTE"],
  },

  // ── BRASIL: GOVERNO / SOCIAL ──────────────────────────────────────────────
  CAIXA_TEM: {
    name: "Caixa Tem / Auxílio Brasil",
    countryCode: "BR",
    category: "GOVERNO_SOCIAL",
    binPrefixes: ["4011", "4055"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_BAIXA",
    bypassMechanism: "UNKNOWN",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Cartão de programa social. Restrições a compras online e internacionais. Exige CPF vinculado. Saldo limitado. Rejeitado por gateways internacionais.",
    alerts: ["CARTAO_SOCIAL_RESTRICAO_ONLINE", "REJEICAO_GATEWAY_INTERNACIONAL"],
  },

  // ── INTERNACIONAL: FINTECHS STEALTH (FRICTIONLESS ALTO) ──────────────────
  REVOLUT: {
    name: "Revolut",
    countryCode: "LT",
    category: "FINTECH_VIRTUAL",
    binPrefixes: ["5375"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: true,
    multipleAttemptsAllowed: true,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "3DS ativo via PSD2/SCA (licença bancária na Lituânia). Alta taxa de frictionless flow (sem desafio visual). CVC expira após 1 uso em cartões virtuais. Não bloqueia em múltiplas tentativas, apenas notifica. Pode exigir selfie em alguns países.",
    alerts: ["FRICTIONLESS_MUITO_ALTO", "CVV_DINAMICO", "MULTIPLAS_TENTATIVAS_SEM_BLOQUEIO"],
  },
  ADVCASH: {
    name: "Advcash",
    countryCode: "EE",
    category: "FINTECH_PREPAGO",
    binPrefixes: ["4263", "4404"],
    threeDSActive: false,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "3DS_NOMINAL",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "3DS nominal: enrolled=Y nos metadados, mas ACS não implementado efetivamente. Campos de autenticação ausentes na resposta do emissor. Alta taxa de aprovação sem desafio.",
    alerts: ["3DS_NOMINAL", "SEM_ACS_REAL", "ALTO_RISCO_FRAUDE"],
  },
  WISE: {
    name: "Wise (TransferWise)",
    countryCode: "GB",
    category: "FINTECH_PREPAGO",
    binPrefixes: ["5399", "5273"],
    threeDSActive: true,
    frictionlessLikelihood: "ALTA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: true,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Comportamento variável por país. Suporta 3DS com biometria e 2FA. Delay falso de aprovação em alguns casos (silent decline). Pode ativar 3DS em fallback quando IP é de país diferente do BIN.",
    alerts: ["COMPORTAMENTO_VARIAVEL_POR_PAIS", "SILENT_DECLINE_RISK", "IP_PAIS_MISMATCH_ATIVA_3DS"],
  },
  CRYPTO_COM: {
    name: "Crypto.com",
    countryCode: "HK",
    category: "CRIPTO",
    binPrefixes: ["4693"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: true,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: true,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "3DS tecnicamente ativo mas não aplicado na prática. CVC gera novo a cada pagamento. Some do log de gateway em alguns casos (silent decline).",
    alerts: ["FRICTIONLESS_MUITO_ALTO", "CVV_DINAMICO", "SILENT_DECLINE_RISK"],
  },
  PAYONEER: {
    name: "Payoneer",
    countryCode: "US",
    category: "FINTECH_PREPAGO",
    binPrefixes: ["5300"],
    threeDSActive: false,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "NO_3DS",
    cvvDynamic: false,
    multipleAttemptsAllowed: true,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Sem 3DS ativo. Permite até 5 tentativas com CVC diferente antes de bloquear. Pouco rastreável.",
    alerts: ["SEM_3DS", "MULTIPLAS_TENTATIVAS_CVC_DIFERENTE", "BRUTE_FORCE_RISK"],
  },
  GREEN_DOT: {
    name: "Green Dot",
    countryCode: "US",
    category: "FINTECH_PREPAGO",
    binPrefixes: ["4388"],
    threeDSActive: false,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "NO_3DS",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Alta taxa de aprovação sem redirect. Muito usado em sites internacionais.",
    alerts: ["SEM_3DS", "ALTO_RISCO_FRAUDE"],
  },
  NETSPEND: {
    name: "Netspend",
    countryCode: "US",
    category: "FINTECH_PREPAGO",
    binPrefixes: ["4411"],
    threeDSActive: false,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "NO_3DS",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Sem autenticação. Comum em operações stealth.",
    alerts: ["SEM_3DS", "ALTO_RISCO_FRAUDE"],
  },
  QONTO: {
    name: "Qonto",
    countryCode: "FR",
    category: "CORPORATIVO",
    binPrefixes: ["5355"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "SCA_EXEMPTION_B2B",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "3DS nominal; quase nunca exigido. Isenção B2B aplicada automaticamente. Pouco auditado.",
    alerts: ["ISENCAO_B2B_PROVAVEL", "3DS_NOMINAL"],
  },
  MONOBANK: {
    name: "Monobank (Universal Bank)",
    countryCode: "UA",
    category: "BANCO_DIGITAL",
    binPrefixes: ["5375"],
    threeDSActive: true,
    frictionlessLikelihood: "ALTA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Implementa 3DS obrigatório via app (Enforced 3D Secure). Confirma transações via canal protegido do app, não SMS. Alta taxa de frictionless para transações de baixo risco.",
    alerts: ["3DS_VIA_APP_OBRIGATORIO", "FRICTIONLESS_POSSIVEL"],
  },
  TINKOFF: {
    name: "Tinkoff Bank",
    countryCode: "RU",
    category: "BANCO_DIGITAL",
    binPrefixes: ["4154"],
    threeDSActive: true,
    frictionlessLikelihood: "ALTA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: true,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Apresenta 3DS, mas ignora se o IP for limpo. Rejeição após timeout em alguns casos.",
    alerts: ["FRICTIONLESS_IP_DEPENDENTE", "SILENT_DECLINE_RISK"],
  },
  N26: {
    name: "N26",
    countryCode: "DE",
    category: "BANCO_DIGITAL",
    binPrefixes: ["5353", "5355"],
    threeDSActive: true,
    frictionlessLikelihood: "MEDIA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "3DS dinâmico. Pode ser bypassado via device hash em alguns casos. Cancela e gera notificação se fallback incompleto.",
    alerts: ["3DS_DINAMICO", "FRICTIONLESS_POSSIVEL_DEVICE_HASH"],
  },
  CHASE: {
    name: "Chase (JPMorgan)",
    countryCode: "US",
    category: "BANCO_TRADICIONAL",
    binPrefixes: ["4147"],
    threeDSActive: true,
    frictionlessLikelihood: "ALTA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Cartão confiável. Muitos passam sem redirect. Cartões empresariais aceitam sem 3DS via isenção B2B.",
    alerts: ["FRICTIONLESS_ALTO", "ISENCAO_B2B_CORPORATIVO"],
  },
  BANK_OF_AMERICA: {
    name: "Bank of America",
    countryCode: "US",
    category: "BANCO_TRADICIONAL",
    binPrefixes: ["4300"],
    threeDSActive: true,
    frictionlessLikelihood: "ALTA",
    bypassMechanism: "SCA_EXEMPTION_LOW_VALUE",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Em valores baixos o 3DS é suprimido via isenção de baixo valor.",
    alerts: ["ISENCAO_BAIXO_VALOR", "FRICTIONLESS_ALTO"],
  },
  WELLS_FARGO: {
    name: "Wells Fargo",
    countryCode: "US",
    category: "BANCO_TRADICIONAL",
    binPrefixes: ["4462"],
    threeDSActive: true,
    frictionlessLikelihood: "ALTA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Em compras digitais stealth-friendly. Muitos cartões ainda sem 3DS completo.",
    alerts: ["FRICTIONLESS_ALTO"],
  },
  BARCLAYS: {
    name: "Barclays",
    countryCode: "GB",
    category: "BANCO_TRADICIONAL",
    binPrefixes: ["4917"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_BAIXA",
    bypassMechanism: "UNKNOWN",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "País com forte exigência de autenticação (FCA/SCA UK). Não permite fallback. 3DS obrigatório.",
    alerts: ["3DS_OBRIGATORIO", "SEM_FALLBACK"],
  },
  NBD_UAE: {
    name: "Emirates NBD",
    countryCode: "AE",
    category: "CORPORATIVO",
    binPrefixes: ["4500"],
    threeDSActive: true,
    frictionlessLikelihood: "MUITO_ALTA",
    bypassMechanism: "SCA_EXEMPTION_B2B",
    cvvDynamic: false,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "Cartões corporativos com bypass total. Mesmo com 3DS ativo, autenticação suprimida por isenção B2B.",
    alerts: ["ISENCAO_B2B_PROVAVEL", "BYPASS_CORPORATIVO_TOTAL"],
  },
  APPLE_CARD: {
    name: "Apple Card (Goldman Sachs)",
    countryCode: "US",
    category: "FINTECH_VIRTUAL",
    binPrefixes: [],
    threeDSActive: true,
    frictionlessLikelihood: "ALTA",
    bypassMechanism: "FRICTIONLESS_3DS2",
    cvvDynamic: true,
    multipleAttemptsAllowed: false,
    silentDeclineRisk: false,
    newCardDelay3DS: false,
    whiteLabel: false,
    technicalNotes: "CVC muda em tempo real. Quebra gateways mal implementados que não suportam CVC dinâmico.",
    alerts: ["CVV_DINAMICO_TEMPO_REAL", "INCOMPATIVEL_GATEWAYS_LEGADOS"],
  },
}

// ─── Lookup Functions ──────────────────────────────────────────────────────

export function findIssuerByBinPrefix(binPrefix: string): IssuerProfile | null {
  const prefix6 = binPrefix.substring(0, 6)
  const prefix4 = binPrefix.substring(0, 4)

  for (const issuer of Object.values(ISSUER_INTELLIGENCE)) {
    for (const prefix of issuer.binPrefixes) {
      const normalizedPrefix = prefix.replace(/\s/g, "")
      if (prefix6.startsWith(normalizedPrefix) || prefix4.startsWith(normalizedPrefix)) {
        return issuer
      }
    }
  }
  return null
}

export function findIssuerByName(issuerName: string): IssuerProfile | null {
  if (!issuerName) return null
  const upper = issuerName.toUpperCase()

  const nameMap: Record<string, string> = {
    "NUBANK": "NUBANK",
    "NU PAGAMENTOS": "NUBANK",
    "BANCO INTER": "BANCO_INTER",
    "INTER": "BANCO_INTER",
    "C6 BANK": "C6_BANK",
    "C6": "C6_BANK",
    "PAGBANK": "PAGBANK",
    "PAGSEGURO": "PAGBANK",
    "CAIXA": "CAIXA",
    "CAIXA ECONOMICA": "CAIXA",
    "ITAU": "ITAU",
    "BRADESCO": "BRADESCO",
    "SANTANDER": "SANTANDER_PJ",
    "REVOLUT": "REVOLUT",
    "WISE": "WISE",
    "ADVCASH": "ADVCASH",
    "CRYPTO.COM": "CRYPTO_COM",
    "PAYONEER": "PAYONEER",
    "GREEN DOT": "GREEN_DOT",
    "NETSPEND": "NETSPEND",
    "TINKOFF": "TINKOFF",
    "N26": "N26",
    "CHASE": "CHASE",
    "JPMORGAN": "CHASE",
    "BANK OF AMERICA": "BANK_OF_AMERICA",
    "WELLS FARGO": "WELLS_FARGO",
    "BARCLAYS": "BARCLAYS",
    "MONOBANK": "MONOBANK",
    "QONTO": "QONTO",
  }

  for (const [key, issuerKey] of Object.entries(nameMap)) {
    if (upper.includes(key)) {
      return ISSUER_INTELLIGENCE[issuerKey] ?? null
    }
  }
  return null
}

export function getIssuerAlerts(issuer: IssuerProfile): string[] {
  return issuer.alerts
}

export function getBypassMechanismDescription(mechanism: BypassMechanism): string {
  const descriptions: Record<BypassMechanism, string> = {
    FRICTIONLESS_3DS2: "3DS 2.0 ativo com fluxo frictionless — autenticação silenciosa pelo ACS do emissor",
    SCA_EXEMPTION_B2B: "Isenção SCA para pagamentos corporativos (PSD2 Secure Corporate Payment Exemption)",
    SCA_EXEMPTION_LOW_VALUE: "Isenção SCA para transações de baixo valor (< €30 / R$150)",
    SCA_EXEMPTION_TRA: "Isenção por Análise de Risco de Transação (TRA) — emissor/adquirente com baixa taxa de fraude",
    "3DS_NOMINAL": "3DS registrado nominalmente (enrolled=Y), mas sem ACS real implementado pelo emissor",
    GATEWAY_FALLBACK: "Gateway não implementa fallback completo de 3DS — transação aprovada sem autenticação",
    NO_3DS: "Sem implementação de 3DS pelo emissor",
    UNKNOWN: "Mecanismo de bypass não determinado",
  }
  return descriptions[mechanism]
}
